2021-10-26 02:32:14 DEBUG Log file at: /home/zhujunhua/workspace/cangjie/utils/test-framework/test_temp/log/HLT/LLVM/stdx_library/Filesystem/os_lchown.cj_cangjie2llvmgc_test_cfg.log
2021-10-26 02:32:14 DEBUG Work directory: /home/zhujunhua/workspace/cangjie/tests/HLT/temp_dir/HLT/LLVM/stdx_library/Filesystem/os_lchown_cj_cangjie2llvmgc_test_cfg_1635213989
2021-10-26 02:32:14 DEBUG execute cmd ===>>>: cjc -backend llvm caserunner.cj -o os_lchown.out os_lchown.cj
2021-10-26 02:32:19 DEBUG return code: 0
2021-10-26 02:32:19 DEBUG stdout : 

2021-10-26 02:32:19 DEBUG stderr : 
@	/home/zhujunhua/workspace/cangjie/tests/HLT/temp_dir/HLT/LLVM/stdx_library/Filesystem/os_lchown_cj_cangjie2llvmgc_test_cfg_1635213989/caserunner.cj:33:5: [33mwarning[0m: unhandled items after throw expr
@	   33 |     }
@	      |     [32m^[0m
@	/home/zhujunhua/workspace/cangjie/tests/HLT/temp_dir/HLT/LLVM/stdx_library/Filesystem/os_lchown_cj_cangjie2llvmgc_test_cfg_1635213989/caserunner.cj:186:19: [33mwarning[0m: 'x' has been defined in the outside of match expression, are you sure using 'x' as a variable pattern here?
@	  186 |         case Some(x) => x
@	      |                   [32m^[0m
@	2 warnings generated

2021-10-26 02:32:19 DEBUG Run time: 4.2, remain time: 3e+02
2021-10-26 02:32:19 DEBUG execute cmd ===>>>:   os_lchown.out  |  /usr/bin/python3 /home/zhujunhua/workspace/cangjie/utils/test-framework/maple_test/compare.py --comment=// os_lchown.cj
2021-10-26 02:32:19 DEBUG return code: 1
2021-10-26 02:32:19 DEBUG stdout : 
+	compare.py input:
+		==============Test Case test case 1 Start==============
+		AssertionError: test failed at 0 
+		AssertionError: test failed at 1 
+		-------------Test Result------------------------------
+		PASS: 2
+		FAIL: 2
+		TOTAL: 4
+		==============Test End=================================
+		
+	
+	compare.py input end
+	
+	Starting Compare:
+	b"It's a assert, flag: scan-not, pattern: AssertionError , result: False, matched at output line: 0"
+	Match End!, Compare Failed

2021-10-26 02:32:19 DEBUG stderr : 

2021-10-26 02:32:19 DEBUG Run time: 0.24, remain time: 3e+02
2021-10-26 02:32:19 ERROR Failed, return code 1 should be 0!
 Log file at: /home/zhujunhua/workspace/cangjie/utils/test-framework/test_temp/log/HLT/LLVM/stdx_library/Filesystem/os_lchown.cj_cangjie2llvmgc_test_cfg.log
